<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\Internal\" />
    <Folder Include="Middleware\Exceptions\" />
    <Folder Include="Middleware\Apis\" />
  </ItemGroup>

</Project>
